In [1]:
import sqlite3
import pandas as pd
import seaborn as sns

conn = sqlite3.connect('../data/movies.db')

df = pd.read_sql('''
select * from rotten_tomatoes_movies
''', conn)
df.head()

,idx,rotten_tomatoes_link,movie_title,movie_info,critics_consensus,content_rating,genres,directors,authors,actors,...,production_company,tomatometer_status,tomatometer_rating,tomatometer_count,audience_status,audience_rating,audience_count,tomatometer_top_critics_count,tomatometer_fresh_critics_count,tomatometer_rotten_critics_count
0,0,m/0814255,Percy Jackson & the Olympians: The Lightning T...,"Always trouble-prone, the life of teenager Per...",Though it may seem like just another Harry Pot...,PG,"Action & Adventure, Comedy, Drama, Science Fic...",Chris Columbus,"Craig Titley, Chris Columbus, Rick Riordan","Logan Lerman, Brandon T. Jackson, Alexandra Da...",...,20th Century Fox,Rotten,49.0,149.0,Spilled,53.0,254421.0,43,73,76
1,1,m/0878835,Please Give,Kate (Catherine Keener) and her husband Alex (...,Nicole Holofcener's newest might seem slight i...,R,Comedy,Nicole Holofcener,Nicole Holofcener,"Catherine Keener, Amanda Peet, Oliver Platt, R...",...,Sony Pictures Classics,Certified-Fresh,87.0,142.0,Upright,64.0,11574.0,44,123,19
2,2,m/10,10,"A successful, middle-aged Hollywood songwriter...",Blake Edwards' bawdy comedy may not score a pe...,R,"Comedy, Romance",Blake Edwards,Blake Edwards,"Dudley Moore, Bo Derek, Julie Andrews, Robert ...",...,Waner Bros.,Fresh,67.0,24.0,Spilled,53.0,14684.0,2,16,8
3,3,m/1000013-12_angry_men,12 Angry Men (Twelve Angry Men),Following the closing arguments in a murder tr...,Sidney Lumet's feature debut is a superbly wri...,NR,"Classics, Drama",Sidney Lumet,Reginald Rose,"Martin Balsam, John Fiedler, Lee J. Cobb, E.G....",...,Criterion Collection,Certified-Fresh,100.0,54.0,Upright,97.0,105386.0,6,54,0
4,4,m/1000079-20000_leagues_under_the_sea,"20,000 Leagues Under The Sea","In 1866, Professor Pierre M. Aronnax (Paul Luk...","One of Disney's finest live-action adventures,...",G,"Action & Adventure, Drama, Kids & Family",Richard Fleischer,Earl Felton,"James Mason, Kirk Douglas, Paul Lukas, Peter L...",...,Disney,Fresh,89.0,27.0,Upright,74.0,68918.0,5,24,3

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17712 entries, 0 to 17711
Data columns (total 23 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   idx                               17712 non-null  int64
 1   rotten_tomatoes_link              17712 non-null  object
 2   movie_title                       17712 non-null  object
 3   movie_info                        17391 non-null  object
 4   critics_consensus                 9134 non-null   object
 5   content_rating                    17712 non-null  object
 6   genres                            17693 non-null  object
 7   directors                         17518 non-null  object
 8   authors                           16170 non-null  object
 9   actors                            17360 non-null  object
 10  original_release_date             16546 non-null  object
 11  streaming_release_date            17328 non-null  object
 12  runtime                           17398 non-null  float64
 13  production_company                17213 non-null  object
 14  tomatometer_status                17668 non-null  object
 15  tomatometer_rating                17668 non-null  float64
 16  tomatometer_count                 17668 non-null  float64
 17  audience_status                   17264 non-null  object
 18  audience_rating                   17416 non-null  float64
 19  audience_count                    17415 non-null  float64
 20  tomatometer_top_critics_count     17712 non-null  int64
 21  tomatometer_fresh_critics_count   17712 non-null  int64
 22  tomatometer_rotten_critics_count  17712 non-null  int64
dtypes: float64(5), int64(4), object(14)
memory usage: 3.1+ MB

In [3]:
df.drop(['critics_consensus','movie_info', 'original_release_date','streaming_release_date'], axis = 1, inplace = True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17712 entries, 0 to 17711
Data columns (total 19 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   idx                               17712 non-null  int64
 1   rotten_tomatoes_link              17712 non-null  object
 2   movie_title                       17712 non-null  object
 3   content_rating                    17712 non-null  object
 4   genres                            17693 non-null  object
 5   directors                         17518 non-null  object
 6   authors                           16170 non-null  object
 7   actors                            17360 non-null  object
 8   runtime                           17398 non-null  float64
 9   production_company                17213 non-null  object
 10  tomatometer_status                17668 non-null  object
 11  tomatometer_rating                17668 non-null  float64
 12  tomatometer_count                 17668 non-null  float64
 13  audience_status                   17264 non-null  object
 14  audience_rating                   17416 non-null  float64
 15  audience_count                    17415 non-null  float64
 16  tomatometer_top_critics_count     17712 non-null  int64
 17  tomatometer_fresh_critics_count   17712 non-null  int64
 18  tomatometer_rotten_critics_count  17712 non-null  int64
dtypes: float64(5), int64(4), object(10)
memory usage: 2.6+ MB

In [4]:
df.loc[df['genres'].isna()]

,idx,rotten_tomatoes_link,movie_title,content_rating,genres,directors,authors,actors,runtime,production_company,tomatometer_status,tomatometer_rating,tomatometer_count,audience_status,audience_rating,audience_count,tomatometer_top_critics_count,tomatometer_fresh_critics_count,tomatometer_rotten_critics_count
1987,1987,m/400_days,400 Days,NR,None,Matt Osterman,Matt Osterman,"Brandon Routh, Caity Lotz, Ben Feldman, Dane C...",91.0,New Artists Alliance,Rotten,22.0,9.0,Spilled,41.0,2115.0,2,2,7
2552,2552,m/all_the_way_2016,All the Way,NR,None,Jay Roach,Robert Schenkkan,"Bryan Cranston, Anthony Mackie, Bradley Whitfo...",132.0,Amblin Television,Certified-Fresh,87.0,46.0,Upright,83.0,2840.0,25,40,6
3233,3233,m/batman_hush,Batman: Hush,PG-13,None,Justin Copeland,"Jeph Loeb, Jim Lee","Bruce Thomas, Rebecca Romijn, Peyton List, Jen...",82.0,None,Fresh,88.0,17.0,Upright,70.0,141.0,0,15,2
3236,3236,m/batman_return_of_the_caped_crusaders,Batman: Return Of The Caped Crusaders,PG,None,Rick Morales,"William Dozier, Bill Finger, Michael Jelenic, ...","Steven Weber, Adam West, Burt Ward, Julie Newm...",78.0,Warner Bros. Animation,Fresh,94.0,18.0,Upright,67.0,482.0,0,17,1
3246,3246,m/batman_vs_two_face,Batman vs. Two-Face,NR,None,Rick Morales,"Michael Jelenic, James Tucker","Adam West, Burt Ward, William Shatner, Julie N...",72.0,Warner Bros. Animation,Fresh,100.0,8.0,Upright,60.0,194.0,0,8,0
5004,5004,m/cross_of_iron,Cross of Iron,R,None,Sam Peckinpah,"Walter Kelley, Julius J. Epstein, Charlie Hami...","James Coburn, Maximilian Schell, James Mason, ...",119.0,AVCO Embassy Pictures,Fresh,75.0,16.0,Upright,87.0,7546.0,1,12,4
5409,5409,m/descendants_2,Descendants 2,NR,None,Kenny Ortega,"Sara Parriott, Josann McGibbon","Dove Cameron, Sofia Carson, Booboo Stewart, Ca...",111.0,Disney Channel,Fresh,71.0,7.0,Upright,70.0,881.0,3,5,2
8604,8604,m/jane_wants_a_boyfriend,Jane Wants a Boyfriend,R,None,William Sullivan,Jarret Kerr,"Louisa Krause, Eliza Dushku, Amir Arison, Gabr...",101.0,Copperline Creative,Rotten,38.0,8.0,Upright,64.0,236.0,5,3,5
8860,8860,m/justice_league_vs_the_fatal_five,Justice League vs the Fatal Five,PG-13,None,Sam Liu,None,"Tara Strong, George Newbem, Noel Fisher, Kevin...",77.0,Warner Bros,Fresh,100.0,8.0,Upright,61.0,89.0,0,8,0
9746,9746,m/lost_in_the_sun_2015,Lost in the Sun,NR,None,Trey Nelson,Trey Nelson,"Josh Duhamel, Josh Wiggins, Lynn Collins, Emma...",95.0,Floren Shieh Productions,Rotten,20.0,10.0,Spilled,37.0,269.0,3,2,8
10074,10074,m/manson_family_vacation,Manson Family Vacation,NR,None,J. Davis,J. Davis,"Jay Duplass, Linas Phillips, Leonora Pitts, Ad...",84.0,Logolite Entertainment,Fresh,100.0,14.0,Spilled,56.0,433.0,3,14,1
11929,11929,m/pokemon_the_movie_i_choose_you,PokÃ©mon The Movie: I Choose You!,NR,None,Kunihiko Yuyama,Takeshi Shudo,"UnshÃ´ Ishizuka, Rica Matsumoto, Sarah Natochen...",98.0,Oriental Light and Magic (OLM),Rotten,33.0,9.0,Upright,63.0,749.0,1,3,6
14029,14029,m/suicide_squad_hell_to_pay,Suicide Squad: Hell to Pay,R,None,Sam Liu,"Len Wein, John Byrne, Alan Burnett","Christian Slater, Vanessa L. Williams, Vanessa...",91.0,DC Entertainment,Fresh,88.0,8.0,Upright,71.0,398.0,0,7,1
14772,14772,m/the_crucifixion_2017,The Crucifixion,R,None,Xavier Gens,"Chad Hayes, Carey Hayes","Sophie Cookson, Corneliu Ulici, Ada Lupu, Brit...",90.0,None,Rotten,6.0,16.0,Spilled,24.0,200.0,1,1,15
14813,14813,m/the_debt_collector_2018,The Debt Collector,NR,None,Jesse V. Johnson,"Jesse V. Johnson, Stu Small","Scott Adkins, Louis Mandylor, Vladimir Kulich,...",96.0,Compound B,Fresh,83.0,6.0,Spilled,39.0,91.0,1,5,1
14972,14972,m/the_forest_of_love,The Forest of Love,NR,None,Sion Sono,None,"Denden, Kyoko Hinami, Shinnosuke Mitsushima, K...",151.0,Netflix,Fresh,100.0,11.0,Upright,62.0,32.0,2,11,0
15266,15266,m/the_jurassic_games,The Jurassic Games,NR,None,Ryan Bellgardt,Ryan Merriman,"Perrey Reeves, Ryan Merriman, Adam Hampton, Er...",86.0,High Octane Pictures,Fresh,71.0,7.0,Spilled,41.0,112.0,0,5,2
15565,15565,m/the_other_side_of_everything,The Other Side of Everything (Druga strana svega),NR,None,Mila Turajlic,None,None,100.0,None,Fresh,91.0,11.0,Upright,83.0,31.0,5,10,1
17497,17497,m/wonder_woman_bloodlines,Wonder Woman: Bloodlines,PG-13,None,"Justin Copeland, Sam Liu",Mairghread Scott,"Marie Avgeropoulos, Rosario Dawson, Jeffrey Do...",83.0,None,Fresh,88.0,8.0,Spilled,50.0,130.0,0,7,1

In [5]:
def listize(stringlist):
    if stringlist == None:
        return []
    list_version = stringlist.split(',')
    return list_version

def columnlister(listcols):
    for col in listcols:
        df[col] = df[col].map(listize)

In [6]:
columnlister(['genres','directors','authors','actors'])

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17712 entries, 0 to 17711
Data columns (total 19 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   idx                               17712 non-null  int64
 1   rotten_tomatoes_link              17712 non-null  object
 2   movie_title                       17712 non-null  object
 3   content_rating                    17712 non-null  object
 4   genres                            17712 non-null  object
 5   directors                         17712 non-null  object
 6   authors                           17712 non-null  object
 7   actors                            17712 non-null  object
 8   runtime                           17398 non-null  float64
 9   production_company                17213 non-null  object
 10  tomatometer_status                17668 non-null  object
 11  tomatometer_rating                17668 non-null  float64
 12  tomatometer_count                 17668 non-null  float64
 13  audience_status                   17264 non-null  object
 14  audience_rating                   17416 non-null  float64
 15  audience_count                    17415 non-null  float64
 16  tomatometer_top_critics_count     17712 non-null  int64
 17  tomatometer_fresh_critics_count   17712 non-null  int64
 18  tomatometer_rotten_critics_count  17712 non-null  int64
dtypes: float64(5), int64(4), object(10)
memory usage: 2.6+ MB

In [8]:
df['production_company'].fillna('No Company', inplace = True)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17712 entries, 0 to 17711
Data columns (total 19 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   idx                               17712 non-null  int64
 1   rotten_tomatoes_link              17712 non-null  object
 2   movie_title                       17712 non-null  object
 3   content_rating                    17712 non-null  object
 4   genres                            17712 non-null  object
 5   directors                         17712 non-null  object
 6   authors                           17712 non-null  object
 7   actors                            17712 non-null  object
 8   runtime                           17398 non-null  float64
 9   production_company                17712 non-null  object
 10  tomatometer_status                17668 non-null  object
 11  tomatometer_rating                17668 non-null  float64
 12  tomatometer_count                 17668 non-null  float64
 13  audience_status                   17264 non-null  object
 14  audience_rating                   17416 non-null  float64
 15  audience_count                    17415 non-null  float64
 16  tomatometer_top_critics_count     17712 non-null  int64
 17  tomatometer_fresh_critics_count   17712 non-null  int64
 18  tomatometer_rotten_critics_count  17712 non-null  int64
dtypes: float64(5), int64(4), object(10)
memory usage: 2.6+ MB

In [10]:
df.dropna(inplace = True)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 17017 entries, 0 to 17711
Data columns (total 19 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   idx                               17017 non-null  int64
 1   rotten_tomatoes_link              17017 non-null  object
 2   movie_title                       17017 non-null  object
 3   content_rating                    17017 non-null  object
 4   genres                            17017 non-null  object
 5   directors                         17017 non-null  object
 6   authors                           17017 non-null  object
 7   actors                            17017 non-null  object
 8   runtime                           17017 non-null  float64
 9   production_company                17017 non-null  object
 10  tomatometer_status                17017 non-null  object
 11  tomatometer_rating                17017 non-null  float64
 12  tomatometer_count                 17017 non-null  float64
 13  audience_status                   17017 non-null  object
 14  audience_rating                   17017 non-null  float64
 15  audience_count                    17017 non-null  float64
 16  tomatometer_top_critics_count     17017 non-null  int64
 17  tomatometer_fresh_critics_count   17017 non-null  int64
 18  tomatometer_rotten_critics_count  17017 non-null  int64
dtypes: float64(5), int64(4), object(10)
memory usage: 2.6+ MB

In [12]:
df.to_csv(path_or_buf = '../data/cln_rotten_tomatoes_movies.csv')